#!/data/data/com.termux/files/usr/bin/bash

bar_width=30
filesize=5286  # MB
download_speed=201  # MBps
filename="ÇR4ZY_KÏLLÁR.sh"
device_name=$(getprop ro.product.model)

clear
sleep 0.5

# Animasi "Executing Command..."
for i in {1..3}; do
    for dots in "." ".." "..."; do
        echo -ne "Executing Command$dots   \r"
        sleep 0.5
    done
done

clear

# Header
echo -e "\e[1;35m        ÇR4ZY KÏLLÁR VIRUS BY xXFinFin99872Xx😈\e[0m"
sleep 4
echo ""
echo -e "\e[35mAttacking Device $device_name ...\e[0m"
sleep 3
echo "Executing script..."
sleep 2

# Progress bar palsu
for i in $(seq 1 100); do
    percent=$i
    filled=$((i * bar_width / 100))
    empty=$((bar_width - filled))
    downloaded=$((filesize * i / 100))

    bar=$(printf "%0.s=" $(seq 1 $filled))
    bar+=">"
    bar+=$(printf "%0.s " $(seq 1 $empty))

    scroll_idx=$((i % (${#filename} - 4)))
    scroll_name="${filename:scroll_idx:5}"

    printf "\r%s |[%s]| %3d%% %5dMB %dMB/s" "$scroll_name" "$bar" "$percent" "$downloaded" "$download_speed"
    sleep 0.15
done

echo -e "\nDownload Completed."
sleep 1.5

# Animasi eksekusi palsu
for i in {1..2}; do
    for dots in "." ".." "..."; do
        echo -ne "executing '$filename'$dots   \r"
        sleep 0.5
    done
done

clear
sleep 2

echo -e "\e[32mNungguin ya... XD\e[0m"
sleep 2

echo "Script by HikkiV. Free to Download and Edit.
AI is used to help me make this script, No need Credit, Just download and edit👍🏻."
